### ISSUE TITLE
add trim feature for 2d files (ie adcp)

### ISSUE THREAD

**Issue by NOAA-Strausz** [NOAA-PMEL/EcoFOCI_MooringAnalysis#4]
Make part of time tools utility if possible.

**Comment by shaunwbell** [comment]
Need to update documents but worked on two test cases.

**Comment by shaunwbell** [comment]
updated so that 'lat' and 'lon' variable keys are recognized as are 'latitude' and 'longitude'

May still need to apply this to the 'dep' vs 'depth' variable

**Comment by shaunwbell** [comment]
I also suppressed the numpy/pandas import warning.
